---
- name: Create folders on remote server
  hosts: server1
  become: yes
  vars:
    tenant_id: "{{ tenant_id }}"  
    media_path: "{{ media_path }}"
  tasks:
    - name: Check if /var/www directory exists
      stat:
        path: /var/www
      register: www_directory

    - name: Create /var/www directory if it doesn't exist
      file:
        path: /var/www
        state: directory
      when: not www_directory.stat.exists

    - name: Create folder For Merch
      file:
        path: "/var/www/Merchandising_API_{{ tenant_id }}" 
        state: directory

    - name: Create folder for Tracker
      file:
        path: "/var/www/Tracker_Maker_Api_{{ tenant_id }}"
        state: directory

    - name: Create folder For  Media
      file:
        path: "{{ media_path }}_{{ tenant_id }}"
        state: directory

