---
- name: Install PostgreSQL 12 and configure password
  hosts: server1
  become: yes
  tasks:
    - name: Install psycopg2 Python library
      package:
        name: python3-psycopg2  # This might vary based on your system, adjust as needed
        state: present
      become: yes
      become_user: root

    - name: Create the file repository configuration
      shell: >
        sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

    - name: Import the repository signing key
      shell: >
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

    - name: Update the package lists
      apt:
        update_cache: yes

    - name: Install PostgreSQL 12
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - postgresql-12
        - postgresql-client-12
        - postgresql-contrib-12


    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

    - name: Set PostgreSQL password
      postgresql_user:
        name: postgres
        password: "pass"
        encrypted: yes
      become: yes
      become_user: postgres
    

    - name: Check PostgreSQL version
      command: pg_config --version
      register: postgres_version

    - debug:
        var: postgres_version.stdout
